name: enhanced_avatar_view
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/TheFe91/flutter_avatar_view

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: